# vi jenkins.yaml
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins-server
spec:
  containers:
    - name: jenkins
      image: jenkins:2.60.3
      ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-data
  volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080